### ISSUE TITLE
Metaprofile page for GoG Manuscripts

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/glossing-entries#116]
A new interface is needed for summarizing the metadata for manuscripts included in the collection of witness fragments referenced in the glosses. This is part of #110 and requires two separate interfaces, at least. First is a profile of each manuscript, based on the identifier string in the URL, as per #114. There is no "manuscript object" in RERUM, but the annotations describe the metadata. The list of metadata is first described in #114 but the authoritative list will be maintained here.

The second interface will imagine a clean way to view and navigate all referenced shelfmarks, so that anything that needs to be modified can be found easily without going through a fragment first.

**Comment by cubap** [comment]
These are the fields that should be editable on this page at a minimum.

- shelfmark: msIdentifier, analog IRI for manuscript
- alternate identifier: semantically equivalent variants of the string we choose to use for the IRI
- city: settlement, city, town, etc.
- Repository: named collection at an institution
- Region: where from
- Origin: roundabouts where from
- Date: YYYY
- institution: holding institution
- provenance: memo about movement and history context

**Comment by cubap** [comment]
These names are not yet aligned to a schema, and should be, especially to support things like #117.

**Comment by cubap** [comment]
content description - human readable short

**Comment by cubap** [comment]
From Atria's report:

> Once we have multiple Gloss Transcription Witnesses for each Gloss, we are thinking it would be great to be able to churn out a table that takes the Shelfmark box, folio box, and text box from each Gloss Transcription Witness. 

Ms A | fol. 15r | "gloss text"
--- | --- | ---
Ms B | fol. 16v | "gloss text"
Ms C | fol. 10v | "gloss text"

**Comment by cubap** [comment]
![GoG Manuscript Metaprofile](https://github.com/CenterForDigitalHumanities/glossing-entries/assets/1119165/8b65be7a-efd2-4b24-839f-93cc377d0d9f)

**Comment by thehabes** [comment]
Somewhat present within the app now.  Can be seen at manuscript-profile.html, editable forms will be at manuscript-metdata.html.
