### ISSUE TITLE
New commentary type field on witness fragment

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/glossing-entries#127]
For gloss-transcription.html and gloss-witness.html, we need to add a field to encode the type of commentary along with the gloss we are attaching. Both interfaces need the same encoding.

**Comment by cubap** [comment]
Probably labeled "Gloss format" and encoded as "_glossFormat" unless there are disagreements.

**Comment by cubap** [comment]
A dropdown element with enum [ "marginal", "interlinear", "appendix", "other" ] with none selected as a possible option.

**Comment by thehabes** [comment]
Generally handled by "Notes" right now. However, we imagine more public facing discussion and other commentary which would need to be captured by a distinct input field. This would overload the capabilities of the "Notes" field, which is meant to be internal.
