### ISSUE TITLE
Highlight behavior problem

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/glossing-entries#160]
> I had a quick question for you about a possible glitch I found in Gallery of Glosses. I've been continuing to attach glosses from TPen manifests to glosses already entered in the system and found when I have a TPen sentence highlighted in green and am using the search bar on the right to try and find the glosses to attach it to, if I accidentally hit the enter key (or possibly any key) the highlighted sentence becomes yellow, indicating it is attached, even though I haven’t selected a gloss to attach it to. I’m then unable to highlight that sentence from the manifest to attach it as each time I highlight it the error message comes up that says “You selection contained text marked for another section.” I also can’t remove the highlighting through the normal method of selecting the gloss it's attached to and clicking “delete the witness” as it isn’t technically attached to any gloss. Any ideas how to undo the highlighting so I can attach these?

Let's let chat summarize for us...

## Issue
When I highlight a TPen sentence in green and use the search bar on the right to find the glosses to attach it to, if I accidentally hit the enter key (or possibly any key), the highlighted sentence becomes yellow, indicating it is attached, even though I haven’t selected a gloss to attach it to. I’m then unable to highlight that sentence from the manifest to attach it as each time I highlight it the error message comes up that says “You selection contained text marked for another section.” I also can’t remove the highlighting through the normal method of selecting the gloss it's attached to and clicking “delete the witness” as it isn’t technically attached to any gloss.

## Steps to Reproduce
1. Highlight a TPen sentence in green.
2. Use the search bar on the right to find the glosses to attach it to.
3. Accidentally hit the enter key (or possibly any key).
4. Observe that the highlighted sentence becomes yellow, indicating it is attached, even though no gloss has been selected.
5. Attempt to highlight the sentence from the manifest to attach it.
6. Observe that the error message comes up that says “You selection contained text marked for another section.”
7. Attempt to remove the highlighting through the normal method of selecting the gloss it's attached to and clicking “delete the witness.”
8. Observe that the highlighting cannot be removed as it isn’t technically attached to any gloss.

## Expected Behavior
The highlighted sentence should not become yellow unless it is attached to a gloss.

## Actual Behavior
The highlighted sentence becomes yellow even though it is not attached to any gloss.

**Comment by thehabes** [comment]
Holy moly.  Upon testing, the "Enter" key does actually fire the submit for the TextWitness form.  Essentially it clicks a phantom "attach" button.  It does not appear to actually attach it to any specific Gloss but does make the TextWitness object.  What the what.

**Comment by thehabes** [comment]
Boils down to "Enter" while focused on an input within a DEER form ends up performing the submit, and it should not.

**Comment by thehabes** [comment]
Appears localized to the WitnessForm on gloss-transcription.html.  Need to trace through the submit process for that form and see why the onsubmit is firing when it shouldn't.  Other forms in the app do not behave this way and appear to ignore the 'Enter'.

**Comment by thehabes** [comment]
From Joseph Grone

> I reloaded the page after being away for a while, just to make sure everything was going to work properly. This, of course, cleared the contents of the text boxes. After highlighting some text (and thereby populating the Text field and the Gloss filter field), I realized that I hadn’t put the shelfmark back in its field. After reentering that information, I inadvertently hit Enter. Doing this ended up submitting the text “hic per spem, illic per rem” as a witness, but not attaching it to any particular gloss.

This bug needs to be prioritized and fixed.
