### ISSUE TITLE
Gloss Transcription Form Inputs

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/glossing-entries#239]
- Shelfmark or Short Citation: “Enter manuscript shelfmark or short bibliographic citation of author and title for the witness, e.g. ‘St. Gall, Stiftsbibliothek 132’ or ‘Kuttner, Repertorium’.”
- Folio or Page [new]: “Enter the folio number or page number from this witness where this instance of the gloss is found”
- Text: “Make sure this is the version of the gloss text as found in this witness.”
- Language: [insert dropdown]
- Gloss Location: [insert dropdown]
- Glossator Hand [new]: [insert dropdown: original gloss hand; later gloss hand]  
- Image Link: “If available, provide IIIF crop tool link or other link to image of this particular witness fragment.”
- Tags [new]: “Only add a tag here if you need to add a new tag for this version of the gloss that does not appear in the main gloss entry.”
- Notes [new]:

**Comment by cubap** [comment]
>Text: “Make sure this is the version of the gloss text as found in this witness.”

In this interface, the text is usually filled by highlighting, so this feels like a strange instruction.
