### ISSUE TITLE
New NG 'Modal'

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/glossing-entries#34]
Specifically in the context of `gloss-transcription.html`.  Once a user has formed the Witness Fragment, they are suggested existing Glosses to pick from to connect the Witness with the Gloss.  However, it is possible that no Glosses are suggestable or that the user intends to create a new Gloss to attach the Witness Fragment to.  This page needs the capability to create and save a new Gloss to act as the selected Gloss for the Witness.

The idea is to do this with a modal so the user interacts with a focused pop up with a form for creating the Gloss.  It should have similar fields to the form on `ng.html`.

It is possible this modal will be used on other pages in the future.  It should create the Gloss and announce the creation.  Pages that use it will interact with its announcements.  That way, it isn't tied to any single page.

**Comment by cubap** [comment]
How are these referenced? Do they become an `@id` in the GLOSS.resources array?
