### ISSUE TITLE
Improve CI/CD

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/glossing-entries#44]
See #36 as well

Make tests and deployments tied to each other.

**Comment by thehabes** [comment]
Only one branch can deploy to https://glossing-dev.rerum.io at a time...

**Comment by TheTuTran** [comment]
Sometimes we want to have a Draft PR open, if only to see the diff. However, Draft PRs will trigger the dev deploy cd.yaml file. We should update the file so it is only triggered by pull_requests that are not drafts.
