### ISSUE TITLE
Depiction for Witnesses

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/glossing-entries#46]
A witness fragment is often real text from a real artifact from real text.  In some cases, the user has access to an image of that artifact.  The user should have the option to provide the link to that image, and further perhaps just the fragment containing the text.  In some cases, this can be automated thanks to Image APIs.  See the difference below.

Whole image as witness
![image](https://github.com/CenterForDigitalHumanities/glossing-entries/assets/3287006/a4e1fa07-3dba-41d3-b51d-8260da533a90)

Just the gloss text from that witness which is the more granular witness
![image](https://github.com/CenterForDigitalHumanities/glossing-entries/assets/3287006/6c699a73-79de-4fc0-a2cc-36b6a84486be)

**Comment by thehabes** [comment]
A note today that the `depiction` value should be an Array, even if of length 0 or 1.  It is because if you select text that goes between columns or pages, it may take multiple distinct depictions to properly display the text snippet images.

**Comment by cubap** [comment]
I would support moving this from `deliverable` to `nice to have`. We get it for free with TPEN, so rendering it should still be deliverable, but we might not need to accommodate recording it for everything (though it is simple to include)
