### ISSUE TITLE
Replace Gloss Collection Name

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/glossing-entries#49]
Right now, the Glosses are added to a collection referenced to as the name `Glossing-Matthew-Named-Glosses`.  The project has morphed and this namespace is no good now.

We want to use the new collection name `GoG-Named-Glosses`.

This replacement needs to happen in the code base and the database at the same time, which means other existing branches using the old namespace will not find the Glosses anymore.

This issue requires careful coordination.

**Comment by cubap** [comment]
hotfixed

**Comment by cubap** [comment]
`db.alpha.updateMany({"body.targetCollection":"Glossing-Matthew-Named-Glosses"},{ $set: {"body.targetCollection":"GoG-Named-Glosses"} } );`
