### ISSUE TITLE
Prod and dev deployments should use respective properties.json file

### ISSUE THREAD

**Issue by AbhilashKotha** [CenterForDigitalHumanities/glossing-entries#94]
@cubap @thehabes As we already have prod values in the properties.json file, we can add it to the gitignore to avoid accidentally pushing dev values. I will go ahead and add it if you feel that is an appropriate solution.

**Comment by cubap** [comment]
the gitignore won't eliminate files already versioned, so this wouldn't "just work". The GitHub Pages deployment needs a properties.json file, so an Action should be set up to copy in one of these files before deployment or something in the scripts needs to select the alternate appropriate for the deployed environment.

**Comment by AbhilashKotha** [comment]
My finding was that the file already exists in the main branch will not be touched and any changes to the file in other branches will not be pushed to the main branch. So the settings will always be production values.

**Comment by cubap** [comment]
https://git-scm.com/docs/gitignore#_notes

Absolutely this should be in the gitignore and untracked. However, that will not address the GH Actions deployment, which needs to know the right values when putting a dev version up on a PR or pushing to prod on a completed PR.

@AbhilashKotha would you like to take this on? Do you prefer we manage it?

**Comment by thehabes** [comment]
Report for Joseph Grone

> I’ve been trying to do some work in the GoG today, but a lot of the data seems to have disappeared again, albeit in a slightly different way from before. In the following manuscript, for example, I had completed several pages, but nothing is highlighted.  Likewise, in most of the glosses, none of the witnesses already attached are displayed. The other gloss data remain, but not the witnesses from this or previous manuscripts.  Finally, it seems that a couple hundred glosses are not currently showing up, since the number is again in the 500s rather than the 700s.
